major refactor, clean up zsh setup, sourceme.sh -> init.zsh, update switch-sh

diff --git a/shell-setup/switch-sh b/shell-setup/switch-sh
--- a/shell-setup/switch-sh
+++ b/shell-setup/switch-sh
@@ -1,6 +1,7 @@
 #!/usr/bin/env zsh
 
 script_dir="${0:a:h}"
+source "$script_dir/utils.zsh"
 homesrc_dir="$script_dir/../home"
 
 opt_dry=0
@@ -12,11 +13,15 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         --dst)
+            if (( $# < 2 )); then
+                echo "missing value for --dst" >&2
+                exit 1
+            fi
             opt_dst=$2
             shift 2
             ;;
         *)
-            echo "Unknown option: $1"
+            echo "unknown option: $1"
             exit 1
             ;;
     esac
@@ -32,33 +37,29 @@ function conf() {
 }
 
 function gen() {
-    local gen_cmd=$1
-    local dst="$opt_dst/$2"
-    echo "> $1\n  -> $dst"
+    local gen_exe=$1
+    local gen_cmd="$1 $2"
+    local dst="$opt_dst/$3"
+
+    if (( ! $+commands[$gen_exe] )); then
+        color red "missing gen exe: $gen_exe"
+        color red "  $gen_cmd"
+        return
+    fi
+
+    echo "> $gen_cmd\n  -> $dst"
     cmds+=("\\mkdir -p $(dirname $dst) && $gen_cmd > $dst")
 }
 
-# list config files/dirs to map
-conf "./zshrc" ".zshrc"
-conf "./sourceme.sh" "sourceme.sh"
-# conf "./aerospace/" ".config/aerospace/"
-conf "./frk/" ".config/frk/"
-conf "./fzf/" ".config/fzf/"
-conf "./ghostty/" ".config/ghostty/"
-conf "./gitui/" ".config/gitui/"
-conf "./sketchybar/" ".config/sketchybar/"
-conf "./starship.toml" ".config/starship.toml"
-conf "./tmux/" ".config/tmux/"
-conf "./wezterm/" ".config/wezterm/"
+function block() {
+    local marker_text=$1
+    local block_file=$2
+    local destination="$opt_dst/$3"
 
-# need to use $homesrc_dir since i dont want to be parsing paths in the command
-gen "lute run $homesrc_dir/karabiner/karabiner.luau" ".config/karabiner/karabiner.json"
+    cmds+=("ensure_block ${(q)marker_text} ${(q)block_file} ${(q)destination}")
+}
 
-# aerospace hack for gaps toggle
-conf "./aerospace/aerospace-base.toml"  ".config/aerospace/aerospace.toml"
-conf "./aerospace/aerospace-base.toml"  ".config/aerospace/aerospace-gaps.toml"
-conf "./aerospace/switch-config.sh"  ".config/aerospace/switch-config.sh"
-gen "toml-cli merge $homesrc_dir/aerospace/aerospace-base.toml $homesrc_dir/aerospace/nogaps-override.toml -o /tmp/out.toml | cat /tmp/out.toml"  ".config/aerospace/aerospace-nogaps.toml"
+source "$script_dir/manifest.zsh"
 
 for cmd in "${cmds[@]}"; do
     if ((opt_dry)); then
